### ISSUE TITLE
bug #1 - Phase 1

### ISSUE THREAD

**Issue by bothaynahazem** [bothaynahazem/Matrix2017_SEProject#5]
The bug we faced in Phase 1 was in the **big example** file where the determinant of B evaluated to _zero_.
After tracing the code, we found that it lies in the **getDeterminant()** function, either the algorithm used is slowing it (the recursive call) or something else we're still unaware of.
Right now, we're working on it and trying to find a better solution.

**Comment by BassemMounir** [comment]
we have changed the algorithm of get_determinant to more fast and safe algorithm
using the LUP decomposition of the matrix to get the determinat value
